version: "3"
services:
  client:
    hostname: iri-client
    container_name: iri-client
    image: iri-client
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/opt/spa
    networks:
      network:
        ipv4_address: 10.100.100.10

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.100.0/24